"""add_cups_name_to_printers

Revision ID: 8a511d439326
Revises: fccc561cb7a5
Create Date: 2026-04-23 17:05:21.035714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a511d439326'
down_revision: Union[str, Sequence[str], None] = 'fccc561cb7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('cups_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printers', 'cups_name')
    # ### end Alembic commands ###
