"""add_printnode_id_to_printers

Revision ID: 9226a0d9a7a8
Revises: 8a511d439326
Create Date: 2026-04-23 18:12:00.758148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9226a0d9a7a8'
down_revision: Union[str, Sequence[str], None] = '8a511d439326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('printnode_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printers', 'printnode_id')
    # ### end Alembic commands ###
