"""add_generated_formulas_table

Revision ID: cdef3d9a2282
Revises: 9226a0d9a7a8
Create Date: 2026-04-27 14:06:49.131490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdef3d9a2282'
down_revision: Union[str, Sequence[str], None] = '9226a0d9a7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.Column('formula_type', sa.String(length=20), nullable=True),
    sa.Column('top_notes', sa.JSON(), nullable=True),
    sa.Column('heart_notes', sa.JSON(), nullable=True),
    sa.Column('base_notes', sa.JSON(), nullable=True),
    sa.Column('sizes', sa.JSON(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_formulas_id'), 'generated_formulas', ['id'], unique=False)
    op.create_index(op.f('ix_generated_formulas_reference'), 'generated_formulas', ['reference'], unique=True)
    op.create_index(op.f('ix_generated_formulas_session_id'), 'generated_formulas', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_formulas_session_id'), table_name='generated_formulas')
    op.drop_index(op.f('ix_generated_formulas_reference'), table_name='generated_formulas')
    op.drop_index(op.f('ix_generated_formulas_id'), table_name='generated_formulas')
    op.drop_table('generated_formulas')
    # ### end Alembic commands ###
