"""add_protocol_to_printers

Revision ID: fccc561cb7a5
Revises: 65c3ca06ebe3
Create Date: 2026-04-23 16:52:28.571659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccc561cb7a5'
down_revision: Union[str, Sequence[str], None] = '65c3ca06ebe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('protocol', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printers', 'protocol')
    # ### end Alembic commands ###
